antool: add new tests

diff --git a/tests/antool/test-parser b/tests/antool/test-parser
--- a/tests/antool/test-parser
+++ b/tests/antool/test-parser
@@ -31,7 +31,7 @@
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
 #
-# test-antool -- test for analyzing tool
+# test/test-parser -- test for antool using match and *.match files
 #
 
 # follow-fork option
@@ -43,23 +43,23 @@ else
 fi
 
 if [ "$3" == "" ]; then
-	echo "Usage: $0 [-f] <path-to-vltrace> <test-app> <test-number>"
+	echo "Usage: $0 [-f] <vltrace-path> <max-string-length> <test-file> <test-number>"
 	echo "   -f - turn on follow-fork"
 	exit 1
 fi
 
 VLTRACE=$1
-TEST_FILE=$2
-TEST_NUM=$3
-
-DIR=/tmp/mnt
-PMEM=pmem
-NONP=nonp
-FILE=file
+MAX_STR_LEN=$2
 
 [ ! -x $VLTRACE ] \
 	&& echo "Error: executable file '$VLTRACE' does not exist" \
 	&& exit 1
+
+TEST_FILE=$3
+TEST_NUM=$4
+
+OPT_VLTRACE="-l bin -r -s $MAX_STR_LEN"
+RUN_VLTRACE="ulimit -l 10240 && ulimit -n 10240 && $VLTRACE $OPT_VLTRACE"
 
 if [ ! -x $TEST_FILE ]; then
 	echo "Error: executable file '$TEST_FILE' does not exist"
@@ -69,6 +69,8 @@ fi
 TEST_DIR=$(dirname $0)
 [ "$TEST_DIR" == "." ] && TEST_DIR=$(pwd)
 
+ANTOOL=$TEST_DIR/../../src/tools/antool/antool.py
+
 FUNCT=$TEST_DIR/helper_functions.sh
 [ ! -f $FUNCT ] \
 	&& echo "Error: missing file: $FUNCT" \
@@ -76,74 +78,52 @@ FUNCT=$TEST_DIR/helper_functions.sh
 
 source $FUNCT
 
-OPT_VLTRACE="$FF -l bin -t -r"
-RUN_VLTRACE="ulimit -l 10240 && ulimit -n 10240 && $VLTRACE $OPT_VLTRACE"
+PATTERN_START="---------------- close 0000000012345678"
+PATTERN_END="---------------- close 0000000087654321"
 
-ANTOOL=$TEST_DIR/../../src/tools/antool/antool.py
+OUT_BIN=output-bin-$TEST_NUM.log
+OUT_TXT=output-txt-$TEST_NUM.log
+OUT_BARE=output-bare-$TEST_NUM.log
+OUT_SORT=output-sort-$TEST_NUM.log
 
-PATTERN_START="close                (0x0000000012345678)"
-PATTERN_END="close                (0x0000000087654321)"
+OUT_VLT=$OUT_BIN
 
-OUTBIN=output-bin-$TEST_NUM.log
-OUT=output-$TEST_NUM.log
-OUTv=output-v-$TEST_NUM.log
-OUTvv=output-vv-$TEST_NUM.log
-OUTf=output-f-$TEST_NUM.log
-OUTfv=output-fv-$TEST_NUM.log
-OUTfvv=output-fvv-$TEST_NUM.log
-OUT_ANTOOL=output-antool-$TEST_NUM.log
-OUTda=output-analysis-$TEST_NUM.log
-
-if [ "$VLTRACE_SKIP" != "1" ]; then
+if [ ! "$VLTRACE_SKIP" ]; then
 	require_superuser
-
-	mkdir -p $DIR/$PMEM
-	mkdir -p $DIR/$NONP
-	touch $DIR/$PMEM/$FILE
-	touch $DIR/$NONP/$FILE
-
-	USER=$(stat --format=%U $TEST_FILE)
-	chown -R $USER.$USER $DIR/*
-
-	# remove all logs and match files of the current test
-	rm -f *-$TEST_NUM.log*
-	echo "$ sudo bash -c \"$RUN_VLTRACE -o $OUTBIN $TEST_FILE $TEST_NUM $DIR $PMEM/$FILE $NONP/$FILE\""
-	sudo bash -c "$RUN_VLTRACE -o $OUTBIN $TEST_FILE $TEST_NUM $DIR $PMEM/$FILE $NONP/$FILE"
+	# remove all logs of the current test
+	rm -f *-$TEST_NUM.log
+	echo "$ sudo bash -c \"$RUN_VLTRACE $FF -o $OUT_VLT $TEST_FILE $TEST_NUM\""
+	sudo bash -c "$RUN_VLTRACE $FF -o $OUT_VLT $TEST_FILE $TEST_NUM"
 fi
 
 set +e
-
-COMMON_OPTS="-t syscalls_table.dat -b $OUTBIN -s -o $OUT_ANTOOL -p $DIR/$PMEM"
-ANTOOL="$ANTOOL $COMMON_OPTS"
-
-echo "$ $ANTOOL > $OUT"
-$ANTOOL > $OUT
-
-echo "$ $ANTOOL -v > $OUTv"
-$ANTOOL -v > $OUTv
-
-echo "$ $ANTOOL -vv > $OUTvv"
-$ANTOOL -vv > $OUTvv
-
-echo "$ $ANTOOL -f > $OUTf"
-$ANTOOL -f > $OUTf
-
-echo "$ $ANTOOL -f -v > $OUTfv"
-$ANTOOL -f -v > $OUTfv
-
-echo "$ $ANTOOL -f -vv > $OUTfvv"
-$ANTOOL -f -vv > $OUTfvv
-
-if [ "$FF" == "" ]; then
-	rm -f $OUT_ANTOOL
-
-	echo "$ $ANTOOL -d > /dev/null"
-	$ANTOOL -d > /dev/null
-
-	grep -e "DEBUG(analysis):" $OUT_ANTOOL | cut -c18- > $OUTda
-	cut_part_file $OUTda "$PATTERN_START" "$PATTERN_END" > cut-$TEST_NUM.log
-fi
-
+echo "$ $ANTOOL -c -s -t syscalls_table.dat -b $OUT_VLT > $OUT_TXT"
+$ANTOOL -c -s -t syscalls_table.dat -b $OUT_VLT > $OUT_TXT
+RV=$?
+[ $RV -ne 0 ] \
+	&& save_logs "*-$TEST_NUM.log" "match-$(basename $TEST_FILE)-$TEST_NUM" \
+	&& exit $RV
+grep --text -e "^0" $OUT_TXT > $OUT_BARE
 set -e
 
-check
+[ $(cat $OUT_BARE | wc -l) -eq 0 ] \
+	&& echo "ERROR: no traces in output of vltrace:" \
+	&& cat $OUT_TXT \
+	&& exit 1
+
+if [ "$FF" == "" ]; then
+	# tests without fork()
+	echo "$ sort $OUT_BARE -o $OUT_SORT"
+	sort $OUT_BARE -o $OUT_SORT
+	cut_part_file $OUT_SORT "$PATTERN_START" "$PATTERN_END" > cut-$TEST_NUM.log
+else
+	# tests with fork()
+	NFILES=$(split_forked_file $OUT_BARE out $TEST_NUM.log)
+	for N in $(seq -s' ' $NFILES); do
+		echo "$ sort out-$N-$TEST_NUM.log -o out-sort-$N-$TEST_NUM.log"
+		sort out-$N-$TEST_NUM.log -o out-sort-$N-$TEST_NUM.log
+		cut_part_file out-sort-$N-$TEST_NUM.log "$PATTERN_START" "$PATTERN_END" > cut-$N-$TEST_NUM.log
+	done
+fi
+
+check_parser
